services:
  database:
    build:
      context: ./database
    container_name: my-postgres-container
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend-db-network
    restart: unless-stopped

  backend:
    build:
      context: ./simpleapi
    container_name: my-backend-api
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://my-postgres-container:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - backend-db-network
      - backend-proxy-network
    restart: on-failure:3

  httpd:
    build:
      context: ./httpd
    container_name: my-httpd
    depends_on:
      - backend
    ports:
      - "81:80"
    networks:
      - backend-proxy-network
    restart: no

networks:
  backend-db-network:
    driver: bridge
  backend-proxy-network:
    driver: bridge

volumes:
  pg_data:
