name: CI DevOps 2025

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "19"

      - name: Build and test with Maven
        working-directory: Lab01/simpleapi
        run: mvn clean verify
