name: CI DevOps 2025

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Build and test with Maven
        working-directory: Lab01/simpleapi
        run: mvn clean verify

  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build backend image
        uses: docker/build-push-action@v6
        with:
          context: Lab01/simpleapi
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api-backend:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build database image
        uses: docker/build-push-action@v6
        with:
          context: Lab01/database
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api-db:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build httpd image
        uses: docker/build-push-action@v6
        with:
          context: Lab01/httpd
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api-httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}
